services:

  redcat_database:
    container_name: redcat_database
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DBNAME}
      MYSQL_USER: ${MARIDB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - /volumes/containers/RedCatFactory/db:/var/lib/mysql
    networks:
      - meicore
      - redcat_internal

  # WordPress CMS
  redcat_site:
    image: wordpress:latest
    restart: unless-stopped
    hostname: redcat.best
    container_name: redcat_site
    environment:
      WORDPRESS_DB_HOST: redcat_database
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_REDIS_HOST: redcat_redis
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=PathPrefix(`/`)"
      - "traefik.http.routers.wordpress.priority=1"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    ports:
      - "4040:80"
    volumes:
      - /volumes/containers/RedCatFactory/site/base:/var/www/html
      - /volumes/containers/RedCatFactory/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - redcat_internal
    depends_on:
      - redcat_database
      - redcat_redis

  # Redis
  redcat_redis:
    image: redis:latest
    container_name: redcat_redis
    restart: unless-stopped
    networks:
      - redcat_internal

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks: [meicore, redcat_internal]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.routers.adminer.middlewares=adminer-strip"
      - "traefik.http.middlewares.adminer-strip.stripprefix.prefixes=/adminer"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    environment:
      # PMA_HOST: redcat_database
      # PMA_USER: ${REDIS_USER}
      # PMA_PASSWORD: ${REDIS_PASSWORD}
      UPLOAD_LIMIT: 1000000000
    depends_on:
     - redcat_database

networks:
  meicore:
    external: true
  redcat_internal:
    driver: bridge
