services:
  
  traefik:
    image: traefik:${TRAEFIK_VERSION:-2.11}
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=${TRAEFIK_DASHBOARD_ENABLED:-true}
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=${TRAEFIK_NETWORK:-traefik-network}
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
      - "${TRAEFIK_DASHBOARD_PORT:-8020}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/letsencrypt:/letsencrypt
      - ./config/traefik:/etc/traefik
    networks:
      - traefik_network
      - meicore
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=traefik-strip"
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/volumes/containers/RedCatFactory/portainer/data:/data"
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.middlewares=portainer-strip"
      - "traefik.http.middlewares.portainer-strip.stripprefix.prefixes=/portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - meicore

  cloudflared_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel run
    environment: 
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - /volumes/containers/RedCatFactory/net:/etc/cloudflared
    networks:
      - meicore

networks:
  traefik-network:
     name: ${TRAEFIK_NETWORK:-traefik_network}
     driver: bridge
     ipam:
      config:
        - subnet: ${SUBNET_CORE:-172.20.0.0/16}

  meicore:
    name: meicore
    external: true
    driver: bridge
