services:

  redcat_database:
    container_name: redcat_database
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DBNAME}
      MYSQL_USER: ${MARIDB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - /volumes/containers/RedCatFactory/db:/var/lib/mysql
    networks:
      - redcat_internal

  # WordPress CMS
  redcat_site:
    image: wordpress:latest
    restart: unless-stopped
    hostname: redcat.best
    container_name: redcat_site
    environment:
      WORDPRESS_DB_HOST: redcat_database
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_REDIS_HOST: redcat_redis
    labels:
      - "traefik.enable=true"
      # Main wordpress routing
      - "traefik.http.routers.wordpress.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wordpress.middlewares=wordpress-strip"
      # Strip prefix middleware
      - "traefik.http.middlewares.wordpress-strip.stripprefix.prefixes=/wordpress"
      - "traefik.http.services.wordpress.loadbalancer.server.port=4040"
    ports:
      - "4040:80"
    volumes:
      - /volumes/containers/RedCatFactory/site/base:/var/www/html
      - /volumes/containers/RedCatFactory/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - redcat_internal
      - proxy_network
    depends_on:
      - redcat_database
      - redcat_redis

  # Redis
  redcat_redis:
    image: redis:latest
    container_name: redcat_redis
    restart: unless-stopped
    networks:
      - redcat_internal

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks: 
      - redcat_internal
      - proxy_network
    ports:
      - "8181:80"
    labels:
      - "traefik.enable=true"
      # Main adminer routing
      - "traefik.http.routers.adminer.rule=Host(`${DOMAIN}`) && PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.adminer.middlewares=adminer-strip"
      # Strip prefix middleware
      - "traefik.http.middlewares.adminer-strip.stripprefix.prefixes=/adminer"
      - "traefik.http.services.adminer.loadbalancer.server.port=8000"
    depends_on:
     - redcat_database

networks:
  redcat_internal:
    driver: bridge

  proxy_network:
    external: true
    name: ${TRAEFIK_NETWORK:-proxy_network}