services:

  redcat_database:
    container_name: redcat_database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - "../../environments/.prod.env"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DBNAME}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ${REDCATBEST_CONTAINERS}/web/db:/var/lib/mysql
    networks:
      - redcat_internal

  # WordPress CMS
  redcat_site:
    image: wordpress:latest
    restart: unless-stopped
    env_file:
      - "../../environments/.prod.env"
    container_name: redcat_site
    environment:
      WORDPRESS_DB_HOST: redcat_database
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_REDIS_HOST: redcat_redis
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${WORDPRESS_DOMAIN}');
        define('WP_SITEURL', 'https://${WORDPRESS_DOMAIN}');
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redcat_site.rule=Host(`${WORDPRESS_DOMAIN}`)"
      - "traefik.http.routers.redcat_site.service=redcat_site"
      - "traefik.http.routers.redcat_site.entrypoints=websecure"
      - "traefik.http.routers.redcat_site.priority=1"  # LOW priority
      - "traefik.http.routers.redcat_site.tls=true"
      - "traefik.http.routers.redcat_site.tls.certresolver=letsencrypt"
      - "traefik.http.services.redcat_site.loadbalancer.server.port=80"
      - "traefik.http.services.redcat_site.loadbalancer.passhostheader=true"
      # Middlewares
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.http.middlewares.wp-cors.headers.accessControlAllowOriginList=${ORIGIN_LIST}"
      - "traefik.http.middlewares.wp-cors.headers.accessControlAllowHeaders=${ALLOW_HEADERS}"
      - "traefik.http.middlewares.wp-cors.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.routers.redcat_site.middlewares=wp-cors, compresstraefik"
      - "traefik.docker.network=proxy_network"
    volumes:
      - ${REDCATBEST_CONTAINERS}/web/site/base:/var/www/html
      - ${REDCATBEST_CONTAINERS}/web/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - redcat_internal
      - proxy_network
    depends_on:
      - redcat_database
      - redcat_redis

  # Redis
  redcat_redis:
    image: redis:latest
    container_name: redcat_redis
    restart: unless-stopped
    networks:
      - redcat_internal

networks:
  redcat_internal:
    driver: bridge

  proxy_network:
    external: true
    name: ${TRAEFIK_NETWORK:-proxy_network}


