services:

  redcat_database_woo:
    container_name: redcat_database_woo
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3304:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DBNAME}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ${SHOP_CONTAINERS}/shop/db:/var/lib/mysql
    networks:
      - redcat_internal_shop

  # WordPress CMS
  redcat_shop:
    image: wordpress:latest
    restart: unless-stopped
    container_name: redcat_shop
    environment:
      WORDPRESS_DB_HOST: redcat_database_woo
      WORDPRESS_DB_USER: ${WOO_USER}
      WORDPRESS_DB_PASSWORD: ${WOO_PASSWORD}
      WORDPRESS_DB_NAME: ${WOO_DB_NAME}
      WORDPRESS_REDIS_HOST: redcat_redis_shop
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${SHOP_DOMAIN}');
        define('WP_SITEURL', 'https://${SHOP_DOMAIN}');
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redcat_shop.rule=Host(`${SHOP_DOMAIN}`)"
      - "traefik.http.routers.redcat_shop.service=redcat_shop"
      - "traefik.http.routers.redcat_shop.entrypoints=websecure"
      - "traefik.http.routers.redcat_shop.priority=1"  # LOW priority
      - "traefik.http.routers.redcat_shop.tls=true"
      - "traefik.http.routers.redcat_shop.tls.certresolver=letsencrypt"
      - "traefik.http.services.redcat_shop.loadbalancer.server.port=80"
      - "traefik.http.services.redcat_shop.loadbalancer.passhostheader=true"
      # Middlewares
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.http.middlewares.shop-cors.headers.accessControlAllowOriginList=${WOO_ORIGIN_LIST}"
      - "traefik.http.middlewares.shop-cors.headers.accessControlAllowHeaders=${WOO_ALLOW_HEADERS}"
      - "traefik.http.middlewares.shop-cors.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.stip-shop-path.stripprefix.prefixes=/shop"
      - "traefik.http.routers.redcat_shop.middlewares=shop-cors, compresstraefik"
      - "traefik.docker.network=proxy_network"
    volumes:
      - ${SHOP_CONTAINERS}/shop/site/base:/var/www/html
      - ${SHOP_CONTAINERS}/shop/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - redcat_internal_shop
      - proxy_network
    depends_on:
      - redcat_database_woo
      - redcat_redis_shop

  # Redis
  redcat_redis_shop:
    image: redis:latest
    container_name: redcat_redis_shop
    restart: unless-stopped
    networks:
      - redcat_internal_shop

networks:
  redcat_internal_shop:
    driver: bridge

  proxy_network:
    external: true
    name: ${TRAEFIK_NETWORK:-proxy_network}