services:

  redcat_database_woo:
    container_name: redcat_database_woo
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DBNAME}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - /volumes/containers/RedCatFactory/shop/db:/var/lib/mysql
    networks:
      - redcat_internal_shop

  # WordPress CMS
  redcat_shop:
    image: wordpress:latest
    restart: unless-stopped

    container_name: redcat_shop
    environment:
      WORDPRESS_DATABASE_HOST: redcat_database_woo
      WORDPRESS_DATABASE_USER: ${WORDPRESS_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_REDIS_HOST: redcat_redis_shop
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${WORDPRESS_DOMAIN}/shop');
        define('WP_SITEURL', 'https://${WORDPRESS_DOMAIN}/shop');
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redcat_site.rule=Host(`${WORDPRESS_DOMAIN}`) && PathPrefix(`/shop`)"
      - "traefik.http.routers.redcat_site.service=redcat_shop"
      - "traefik.http.routers.redcat_site.entrypoints=websecure"
      - "traefik.http.routers.redcat_site.priority=1"  # LOW priority
      - "traefik.http.routers.redcat_site.tls=true"
      - "traefik.http.routers.redcat_site.tls.certresolver=letsencrypt"
      - "traefik.http.services.redcat_site.loadbalancer.server.port=80"
      - "traefik.http.services.redcat_site.loadbalancer.passhostheader=true"
      # Middlewares
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.http.middlewares.wp-cors.headers.accessControlAllowOriginList=${ORIGIN_LIST}"
      - "traefik.http.middlewares.wp-cors.headers.accessControlAllowHeaders=${ALLOW_HEADERS}"
      - "traefik.http.middlewares.wp-cors.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.routers.redcat_site.middlewares=wp-cors, compresstraefik"
      - "traefik.docker.network=proxy_network"
    volumes:
      - /volumes/containers/RedCatFactory/shop/site/base:/var/www/html
      - /volumes/containers/RedCatFactory/shop/php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - redcat_internal_shop
      - proxy_network
    depends_on:
      - redcat_database_woo
      - redcat_redis_shop

  # Redis
  redcat_redis_shop:
    image: redis:latest
    container_name: redcat_redis_shop
    restart: unless-stopped
    networks:
      - redcat_internal_shop

networks:
  redcat_internal_shop:
    driver: bridge

  proxy_network:
    external: true
    name: ${TRAEFIK_NETWORK:-proxy_network}


